### ISSUE TITLE
React DevTools extension is not enabled for Replay devtools

### ISSUE THREAD

**Issue by bvaughn** [replayio/devtools#6486]
The React DevTools extension is only "enabled" (visible in the browser DevTools) on pages where React has been detected. For some reason (haven't dug in yet) the Replay devtools client isn't detected and so the React DevTools extension will never be enabled.

To "work around this" I have to first visit another website built with React (like https://reactjs.org/), open the browser DevTools, and then navigate _back_ to Replay devtools.

**Comment by hbenl** [comment]
This was probably fixed by RecordReplay/gecko-dev#848, could you recheck?

**Comment by bvaughn** [comment]
Yup! This looks fixed. :)

**Comment by bvaughn** [comment]
@souporserious and I are both seeing this again so I'm re-opening.

**Comment by bvaughn** [comment]
Just to clarify, I believe you are saying that we should add which recordings React DevTools doesn't load for?

I'll try to remember to do that.

**Comment by souporserious** [comment]
On my end this has been due to the browser's React dev tools extension not loading so either Chrome/Brave in my case. I still see it intermittently, but will record a Replay next time it happens!

**Comment by bvaughn** [comment]
I don't think Holger's asking us to record a Replay of the bug happening. I don't think we can, since we can't record a replay of _Chrome extensions_.

I think he's asking if there's a pattern of this bug happening for some recordings and not others– like if there's something _about specific to a recording_ that triggers it.
